name: Dependabot auto-merge
on: 
  pull_request:
    branches:
      - main
      
permissions:
  contents: write
  pull-requests: write

jobs:
  mapping:
    runs-on: ubuntu-latest
    steps:
      - name: Display Repository Owner
        id: show_owner
        env:
          owner: ${{ github.repository_owner }}
        run: echo "Repository Owner = $owner"
      - name: Display Pull Request creator
        id: show_creator
        env:
          creator: ${{ github.event.pull_request.user.login }}
        run: echo "Pull Request creator = $creator"
      - name: Check commit signatures
        uses: dorny/paths-filter@v3
        id: check_signed_commits
        env:
          owner: ${{ github.repository_owner }}
        with:
          filters: |
            commits:
              paths: "any"
              signed-by: $owner